# Jekyll configuration for GitHub Pages
# This file helps prevent build errors

# Exclude directories from Jekyll processing
exclude:
  - node_modules/
  - pcf-components/CustomerList/node_modules/
  - coverage/
  - logs/
  - "*.log"
  - package-lock.json
  - package.json
  - tsconfig.json
  - webpack.config.js
  - .gitignore
  - LICENSE
  - scripts/
  - tests/
  - solutions/
  - plugins/
  - canvas-apps/
  - model-driven-apps/
  - power-automate-flows/
  - dataverse-entities/
  - azure-devops/

# Disable Jekyll plugins that might cause issues
plugins: []

# Use simple HTML serving
permalink: pretty